appId: dev.labloom.app
productName: labloom
directories:
  buildResources: build
  output: dist/release
files:
  - '!**/.vscode/*'
  - '!{main,preload,renderer,shared}/**/*'
  - '!configs/**/*'
  - '!dist/.eslintcache'
  - '!dist/*.tsbuildinfo'
  - '!dist/types/**/*'
  - '!dist/release/**/*'
  - '!{.eslintcache,dev-app-update.yml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,pnpm-lock.yaml,pnpm-workspace.yaml}'
  - '!tsconfig.json'
asarUnpack:
  - resources/**
win:
  executableName: labloom
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  target:
    - AppImage
    - snap
    - deb
  maintainer: labloom.dev
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://labloom.dev/downloads/